id: P198795E5
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA21923
  instance_id: http://purl.bdrc.io/resource/IE21923
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - གེ་སར་སྒྲུང་གི་ཚིག་འགྲེལ་གསལ་སྒྲོན།
  alt_title:
    en-x-mixed:
    - Gliṅ Ge-sar rgyal poʾi sgruṅ gtam gyi tshig ʾgrel gsal sgron /Dkon-mchog-tshe-brtan
      gyis bsgrigs.
    zh-hans:
    - 格萨尔王传词汇住解
  author: http://purl.bdrc.io/resource/P5119
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  volumes:
    b246fdae8805417f881d4a6febdc3ddb:
      title: པོད ༡་གེ་སར་སྒྲུང་གི་ཚིག་འགྲེལ་གསལ་སྒྲོན
      volume_number: 1
      base_file: UT21923_5706_0000.txt
      reference: http://purl.bdrc.io/resource/VLBCE8267B3D3D3B78
      image_group: '5706'
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/W21923
  - http://purl.bdrc.io/resource/MW21923
  ocr_software: Namsel
created_at: '2021-12-22T11:08:05.773556'
last_modified_at: '2021-12-22T11:08:05.773564'
statistics:
  total_words: 59619
  total_non_words: 9015
quality:
  non_words_ratio: 0.15
